version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm start collect && npm start export:toGraphite | nc graphite 2003"
    depends_on:
      - graphite
    tty: true
    container_name: github-metrics-app
    volumes:
      - ./data:/opt/github-metrics/data
      - ./src:/opt/github-metrics/src
    environment:
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_REPO_NAME: ${GITHUB_REPO_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      DATABASE_PATH: ${DATABASE_PATH}

  grafana:
    build: './grafana'
    container_name: github-metrics-grafana
    restart: always
    ports:
      - '3000:3000'

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: github-metrics-graphite
    restart: always
    ports:
      - '80:80'
      - '2003:2003'
      - '2004:2004'
      - '8080:8080'
