{
 "title": "GitHub Stats",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 0 },
   "content": "# Pull request time to merge\n\nDays elapsed between the creation and merge of a pull request."
  },
  {
   "title": "Current Month - All Repositories",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 3 },
   "targets": [
    {
     "target": "averageSeries(github.*.*.pull_requests.*.time_to_merge)"
    }
   ]
  },
  {
   "title": "Trend over the last 3 month by repository",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(smartSummarize(groupByNode(github.*.*.pull_requests.*.time_to_merge, 2, 'sum'), '1w', 'avg'))"
    }
   ]
  },
  {
   "title": "Trend over the last 3 month by PR size",
   "type": "graph",
   "description": "### Pull Request Sizes\n\nThe pull request size calculated based on the total lines of code changed (`total additions + total deletions`).\n\n| Name       | Description                              |\n| ---------- | ---------------------------------------- |\n| `size_XS`  | Denotes a PR that changes 0-9 lines.     |\n| `size_S`   | Denotes a PR that changes 10-29 lines.   |\n| `size_m`   | Denotes a PR that changes 30-99 lines.   |\n| `size_l`   | Denotes a PR that changes 100-499 lines. |\n| `size_xl`  | Denotes a PR that changes 500-999 lines. |\n| `size_xxl` | Denotes a PR that changes 1000+ lines.   |",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "target": "groupByNode(summarize(github.*.*.pull_requests.*.time_to_merge, '1w', 'avg'), 4, 'sum')"
    }
   ]
  },
  {
   "title": "Previous Month - All Repositories",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "averageSeries(github.*.*.pull_requests.*.time_to_merge)"
    }
   ]
  },
  {
   "title": "Two Months ago - All Repositories",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "target": "averageSeries(github.*.*.pull_requests.*.time_to_merge)"
    }
   ]
  },
  {
   "title": "Three Months ago - All Repositories",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "averageSeries(github.*.*.pull_requests.*.time_to_merge)"
    }
   ]
  }
 ]
}